/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;

import java.io.FileNotFoundException;
import java.lang.reflect.Array;

import static org.junit.Assert.*;

public class QuoteTest {

  @Test public void functionalityTestOne() throws FileNotFoundException {
    QuotesFinder heresThing  = new QuotesFinder();
    Quote[] thingToTest = heresThing.quoteArrayCreator();
    assertEquals(Quote[].class, thingToTest.getClass());
  }

  @Test public void functionalityTestTwo() throws FileNotFoundException {
    QuotesFinder heresThing  = new QuotesFinder();
    Quote[] quoteArray = heresThing.quoteArrayCreator();
    int thingToTest = heresThing.random(quoteArray.length);
    int i = 1;
    assertNotNull(String.valueOf(int.class), thingToTest); // how to test that a primitive is it's class/type?
  }

  @Test public void functionalityTestThree() {
    // parse it!
    // object it!
    // ???
    // Success!
  }

  @Test public void functionalityTestFour() {
    // parse it!
    // object it!
    // ???
    // Success!
  }

  @Test public void functionalityTestFive() {
    // parse it!
    // object it!
    // ???
    // Success!
  }
}
