/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.* ;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class QuotesFinder {

    public static void main(String[] args) throws IOException {
        displayQuote();
    }

    public static void displayQuote() throws IOException {
        try {
            QuotesFinder quotesFinder = new QuotesFinder();
            String firstStep = quotesFinder.returnQuoteFromApi();
            saveQuote(firstStep);
            List<Quote> quotesList = quotesFinder.createQuoteArray();
            Quote latestQuote = quotesFinder.singleQuoteOut(firstStep);
            System.out.println(latestQuote);
//            quotesList.add(latestQuote);
            recreateJsonFile(quotesList);
        } catch (IOException e) {
            QuotesFinder backUpQuote = new QuotesFinder();
            System.out.println("Why am I here?" + toStringRandomizer(backUpQuote.createQuoteArray()));
        }
    }

    public String returnQuoteFromApi() throws IOException {
        URL url = new URL("http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en");
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        connection.setRequestMethod("GET");
        BufferedReader input = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        return input.readLine();
    }

    public Quote singleQuoteOut(String jsonString) {
        Gson quote = new Gson();
        //        System.out.println(newQuote);
        return quote.fromJson(jsonString, ForismaticQuote.class);
    }

    public static void saveQuote(String quoteJson) throws IOException {
        String path = "src/main/resources/recentquotes.json";
        System.out.println(quoteJson);
        String file = Files.readString((Paths.get(path)));
        file = file.substring(0, file.length() - 1);
        file += String.format(", %s", quoteJson);
        BufferedWriter writer = new BufferedWriter(new OutputStreamWriter((new FileOutputStream(path)), "UTF8")); // Cp1252 StandardCharsets.UTF_8
        writer.write(file);

        writer.close();
    }

    public List<Quote> createQuoteArray() throws FileNotFoundException {
        Gson quotes = new Gson();
        FileReader quotesFile = new FileReader("src/main/resources/recentquotes.json");
        Quote[] newList = quotes.fromJson(quotesFile, Quote[].class);
        return new ArrayList<>(Arrays.asList(newList));
    }

    public static String toStringRandomizer(List<Quote> toRead) {
        int randomQuoteNumber = random(toRead.size());
        String finalQuote = String.format("\"%s\" was said by the author %s.", toRead.get(randomQuoteNumber).text, toRead.get(randomQuoteNumber).author);
        System.out.println(finalQuote);
        return finalQuote;
    }

    private static int random(int sizeOfRandom){
        return (int) (Math.random() * sizeOfRandom);
    }

    private static void recreateJsonFile(List<Quote> fileToJson) throws IOException {
        Gson output = new Gson();
        BufferedWriter writer = new BufferedWriter(new OutputStreamWriter((new FileOutputStream("src/main/resources/recentquotes.json")), "UTF8")); // Cp1252 StandardCharsets.UTF_8
        writer.write(output.toJson(fileToJson));
    }
}
