/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.* ;

import java.io.FileNotFoundException;
import java.io.FileReader;

public class QuotesFinder {

    public Quote[] quoteArrayCreator() throws FileNotFoundException {
        Gson quotes = new Gson();
        FileReader quotesFile = new FileReader("C:\\Users\\PVOVi\\codefellows\\401\\quotes\\src\\main\\resources\\recentquotes.json");
        System.out.println(quotesFile.toString());
        Quote[] newQuotes = quotes.fromJson(quotesFile, Quote[].class);
        return newQuotes;
    }

    public String toStringRandomizer (Quote[] toRead) {
        int randomQuoteNumber = random(toRead.length);
        String finalQuote = String.format("\"%s\" was said by the author %s.", toRead[randomQuoteNumber].text, toRead[randomQuoteNumber].author);
        System.out.println(finalQuote);
        return finalQuote;
    }

    public int random(int sizeOfRandom){
        int a = (int) (Math.random() * sizeOfRandom);
        return a;
    }
}
